### ISSUE TITLE
asset 1 in the 9.0.0 release: asciidoc-9.0.0.tar.gz extracts to current directory

### ISSUE THREAD

**Issue by pierre-labastie** [asciidoc/asciidoc-py3#123]
When running `tar -xf asciidoc-9.0.0.tar.gz`, the files are extracted to the current directory, while usually, the files are extracted to a subdirectory.

**Comment by MasterOdin** [comment]
Updated the make target to build the archives with a top-level `asciidoc-$(VERSION)` folder that contains all files, instead of having all file be at the top-level in 5fbcc21174acd26f31008e15ab87ff0a33288d27. Updated the tarballs for 9.0.0 as well.

**Comment by pierre-labastie** [comment]
Thanks for the quick fix! Got the new tarball with the updated directory layout, and will include the new version in the [Beyond Linux From Scratch](http://www.linuxfromscratch.org/blfs) book. Thanks also for the move to Python3!

**Comment by MasterOdin** [comment]
No problem! Always happy to hear people are using this work given how long it's been between asciidoc.py releases!
