### ISSUE TITLE
test 16 (LaTeX Filter) produces files which are installed by make install

### ISSUE THREAD

**Issue by eli-schwartz** [asciidoc/asciidoc-py3#133]
The entire doc/ directory gets installed by `make install`, but this test uses `../doc/latex-filter.txt` as a source, and the filter in question ends up writing new files there.

Specifically:

```
doc/latex-filter__1.md5
doc/latex-filter__1.svg
doc/latex-filter__2.md5
doc/latex-filter__2.svg
doc/latex1.md5
doc/latex1.svg
doc/latex2.md5
doc/latex2.png
doc/latex3.md5
doc/latex3.svg
```

These files should not be installed, but if `python3 tests/testasciidoc.py run -n 16` is run before installing, they are.

**Comment by MasterOdin** [comment]
Thanks for filing these issues! As someone who has no knowledge or experience with how distros package stuff, the reports that you and @aerostitch have been super informative.

To solve this, I think the best solution would probably be to define a new `artifacts` directive which defines a list of expected files to be generated from the test, which after running the test and verifying the asciidoc output, check that the files exist, and then delete them. Would this work for you?

**Comment by eli-schwartz** [comment]
Happy to help. :)

That seems like a reasonable solution, my current packaging workaround is to delete those file myself.
