### ISSUE TITLE
API call to return the raw parse tree

### ISSUE THREAD

**Issue by polyglot-jones** [asciidoc/asciidoc-py3#134]
I have a project in mind for which I want to be able to parse a snippet of AsciiDoc text but only as far as obtaining the parse tree. My custom code will take it from there. I really want to keep my project pure Python3, so using just the asciidocapi is appealing. I'd really like to avoid having to go through AsciiDoctor, Pandoc, whatever.

My initial thought is to create a pass-thru backend called `raw` or 'parse-tree` or whatever that outputs the parse tree (or a simplified variation thereof) as json. 

I'll do the legwork, but I'd like some guidance.

1. Is my raw backend idea on track, or is there a better/faster way to get there?
2. I haven't studied any of the current backend code yet. Any suggestions on the best place to start? Any heads up on the good, the bad, and the ugly that I'll find there? 
3. I don't suppose that there's a backend development guide somewhere? What about a hello-world starter backend?

**Comment by elextr** [comment]
The current Asciidoc Python implementation is a stream converter, it doesn't make a parse tree. 

 "Backends" are mostly conversion templates and is documented in the User Guide, so you could probably output some "tree" format instead of HTML or XML.

**Comment by polyglot-jones** [comment]
Oh, that sounds simpler that I feared. Thanks. Closing issue...
