### ISSUE TITLE
formatted manpage for testasciidoc is not distributed in assets

### ISSUE THREAD

**Issue by pierre-labastie** [asciidoc/asciidoc-py3#136]
The MANIFEST.in file has:
doc/a2x.1
doc/asciidoc.1

but not doc/testasciidoc.1

This imposes a build dependency on xsltproc and docbook-xsl when running building from a release tarball. Of course, those are needed at run time, but the machine for building might not be the machine where the programs are run.

**Comment by pierre-labastie** [comment]
Well, maybe the testasciidoc man page shouldn't be required for a regular build (without tests), since testasciidoc is not installed. Or testasciidoc should be installed instead. Up to you...

**Comment by MasterOdin** [comment]
Given that the file clocks in at roughly ~2kb, I would probably just include it for the sake of completeness.
