### ISSUE TITLE
source lines doesnt work

### ISSUE THREAD

**Issue by giuseppe17ita** [asciidoc/asciidoc-py3#149]
`include::myfile.py[lines=40..41]`

this code doesnt work. it show all file lines like `include::myfile[]`

**Comment by MasterOdin** [comment]
Did this ever work in asciidoc-py? I believe this (and a number of include options) are asciidoctor only.

**Comment by giuseppe17ita** [comment]
`include::myfile.py[]` work fine in asciidoc-py
but
`[lines=1..10]` return all the file as above one

**Comment by elextr** [comment]
@giuseppe17ita the `lines=` selector is not supported by Asciidoc-py. It is an Asciidoctor extension.

**Comment by giuseppe17ita** [comment]
there are similar selector? or it can be implemented?

**Comment by MasterOdin** [comment]
This will be included in the 10.0 release.
