### ISSUE TITLE
Fix asciidoc.org Link Rot

### ISSUE THREAD

**Issue by hoadlck** [asciidoc/asciidoc-py3#159]
I have been going thru the website, and found some bad links.  I made a PR to address the ones that I was confident of, but there were some that I could not track down.

This issue may be related to #114.

- Link Dead
This one is internal to the AsciDoc.org site.  It appears that the pdf is not being generated anymore?
https://github.com/asciidoc/asciidoc-py3/blob/8de61a75572b5b8f90c1f87634aa3767472be7a7/website/index.txt#L173-L175

- Link Unresponsive
I am not finding any new location for this with Google.
https://github.com/asciidoc/asciidoc-py3/blob/8de61a75572b5b8f90c1f87634aa3767472be7a7/website/index.txt#L230-L232

- Link Dead
The site seems to have a completely different structure.  And, I don't get any good hit for the content on Google.
https://github.com/asciidoc/asciidoc-py3/blob/8de61a75572b5b8f90c1f87634aa3767472be7a7/website/index.txt#L237-L240

- Dropbox Link Dead
Dropbox URL is dead.  I am not finding any new location for this with Google.
https://github.com/asciidoc/asciidoc-py3/blob/8de61a75572b5b8f90c1f87634aa3767472be7a7/website/index.txt#L251-L255

- Link Dead
Server not found.  I am not finding any new location for this with Google.
https://github.com/asciidoc/asciidoc-py3/blob/8de61a75572b5b8f90c1f87634aa3767472be7a7/website/index.txt#L272-L277

- Link Unresponsive
https://github.com/asciidoc/asciidoc-py3/blob/8de61a75572b5b8f90c1f87634aa3767472be7a7/website/index.txt#L300-L302

- Main Link Unresponsive
The linked article still shows up fine.
https://github.com/asciidoc/asciidoc-py3/blob/8de61a75572b5b8f90c1f87634aa3767472be7a7/website/index.txt#L308-L312

 - Server Unresponsive
I am not seeing any hits on Google for this.
https://github.com/asciidoc/asciidoc-py3/blob/8de61a75572b5b8f90c1f87634aa3767472be7a7/website/index.txt#L369-L372

 - Server Unresponsive
The person mentioned appears to be [here](https://www.nico.schottelius.org/about/) now, but I cannot find any mention of AsciiDoc.
https://github.com/asciidoc/asciidoc-py3/blob/8de61a75572b5b8f90c1f87634aa3767472be7a7/website/index.txt#L406-L407

 - Server Unresponsive
I am not finding any new location for this with Google.
https://github.com/asciidoc/asciidoc-py3/blob/8de61a75572b5b8f90c1f87634aa3767472be7a7/website/index.txt#L419-L420

 - Server Unresponsive
I am not finding any new location for this with Google.
https://github.com/asciidoc/asciidoc-py3/blob/8de61a75572b5b8f90c1f87634aa3767472be7a7/website/index.txt#L431-L432

**Comment by hoadlck** [comment]
I am proposing that any entry which does not have a good link in it be removed.  

There are some entries where there are some links that are good and others that are not.  For these, it may take some more thought.

**Comment by MasterOdin** [comment]
I've spun off the first link (latexmath.pdf) into its own issue (#162) since that's internal to asciidoc-py itself, and with a nice clear solution for it (just add building the pdf to the shell script).

For all the others, I am of the opinion to just remove them. They're dead, and there's better things to spend bandwidth on than trying to find replacements. A broader point here is also not spending too much time digging up old links as the site is probably going to undergo major changes in 2021 as the [AsciiDoc language project](https://projects.eclipse.org/proposals/asciidoc-language) gets further underway and asciidoc.org transitions to them where they'll handle documenting usage of asciidoc in the community.

**Comment by hoadlck** [comment]
Oh, really?  I did not realize that control of asciidoc.org was moving.  I had it in mind that other changes should be made to the site, and was looking in depth to see what was there.

Ironically enough, one of the sections I was thinking of proposing was a Plan section.  A place to describe the different milestones of the project, and what is in store.  It is all well and good to have issues, but they are not concentrated.  Where would the Python AsciiDoc project keep that information?  Is there going to be a new site for the Python implementation?  Or a child site of the current asciidoc.org?

For now, I will delete the dead links mentioned above and push them to #160.

**Comment by MasterOdin** [comment]
Much of the middle paragraph is still in-flux at the moment, and that asciidoc-py would become a subdomain or hosted elsewhere off asciidoc which would transition to be more fully a "AsciiDoc Ecosystem At-Large" type site than asciidoc-py specific.

I do agree that putting a "Plan" section (though I might call it roadmap) could be good, and that can be added to the site as a top-level link under "Changelog".
