### ISSUE TITLE
decode method doesn't exist on string object

### ISSUE THREAD

**Issue by lfkeitel** [asciidoc/asciidoc-py3#16]
The decode method on string objects doesn't exist in Python 3.6 (https://docs.python.org/3/library/stdtypes.html#str.encode). Line 263 in particular is an offender. There may be other uses but I haven't looked. I was able to trigger it by using xhtml as the output format.

**Comment by elextr** [comment]
Line 263 of what file? Link?

**Comment by lfkeitel** [comment]
The main a2x.py file.

**Comment by elextr** [comment]
[here](https://github.com/asciidoc/asciidoc-py3/blob/cd6762bd16b20e5cf19ceaffb8452df912bb5f6e/a2x.py#L263)

**Comment by lfkeitel** [comment]
Yep that's it. When I run with Python 3.6 that line throws saying decide
doesn't exist on str.

**Comment by lfkeitel** [comment]
I meant decode not decide.

**Comment by MasterOdin** [comment]
Yeah, need to detect mode passed to read (and write) and then decode/encode) appropriate within the function to just expect to deal with strings going in and going out.

Do you have a file and arguments you've used to run this to test?

**Comment by elextr** [comment]
Possibly the read should read bytes if encoding is not known, not strings, and then its decoded to Unicode string.  (Pythjon 3 decode() moved to bytes objects).

**Comment by lfkeitel** [comment]
When I get back to my computer I can give you the exact source and command
I used.

**Comment by lfkeitel** [comment]
I ran into the error when building a package for [newsboat](https://github.com/newsboat/newsboat) on Fedora. Its documentation is generated using a2x. The current development version of Fedora uses this package instead of the original Python 2 version and was failing the doc builds. For a quick repro, from the newsboat repository run `a2x -f xhtml doc/faq.txt`. If you would like a specific tag I'm using `r2.11.1`.

**Comment by elextr** [comment]
@lfkeitel Fedora is maybe a bit early off the mark, this is still developmental, see #15 and the repository message.

**Comment by lfkeitel** [comment]
I'm well aware of that. It wasn't my decision. Fedora 29 is going with Python 3 as the default and they're trying their best to prepare. I just have to deal with it. I've already put in a comment with them about it so they may make a patch to the pre-release package until it's fixed upstream. I just thought you would like to know that I ran into the bug.

**Comment by elextr** [comment]
@lfkeitel no problem, thanks for reporting, certainly Fedora should be used to making patches to early release packages, and updating them regularly, its a fairly bleeding edge distro after all :)

**Comment by MasterOdin** [comment]
So looking at this further, it seems that we can either remove the whole encoding check, or rewrite read_file slightly such that it loads the file as a byte string, reads the first line or two to check if there's an encoding and if there is, open the file in that encoding or else just fallback to standard UTF-8?

**Comment by lfkeitel** [comment]
Thanks. This is how asciidoc3 handles it: https://github.com/asciidoc3/asciidoc3/blob/master/a2x3.py#L302. If it helps at all. They just call encode with the detected encoding.

**Comment by MasterOdin** [comment]
I think what you'd probably want to do is something like:
```
with open(filename, 'rb') as open_file:
        contents = open_file.read()
mo = re.search(b'\A<\?xml.* encoding="(.*?)"', contents)
contents = contents.decode(mo.group(1) if mo else 'utf-8')
```
