### ISSUE TITLE
:sectnums: being rendered as text if it comes at the top of an included file

### ISSUE THREAD

**Issue by bzbarsky-apple** [asciidoc/asciidoc-py3#164]
Consider the following situation.  I have `main.adoc` that looks like this:
```
include::one.adoc[]
include::two.adoc[]
```
`one.adoc` looks like this:
```
== First Doc

First doc text
```
and `two.adoc` looks like this:
```
:sectnums:

== Second Doc

Second doc text.
```
When I run `asciidoctor -b html main.adoc` I get `main.html` that looks like this:
```
....
<div class="sect1">
<h2 id="_first_doc">First Doc</h2>
<div class="sectionbody">
<div class="paragraph">
<p>First doc text
:sectnums:</p>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_second_doc">Second Doc</h2>
<div class="sectionbody">
<div class="paragraph">
<p>Second doc text.</p>
...
```
with the `:sectnums:` as part of the rendered text and no section number on the "Second Doc" section, which is not the intent.

If I add a blank line at the top of `two.adoc`, before the `:sectnums:` line, then I get the expected behavior: a section number on "Second Doc" and no rendered `:sectnums:` text....

**Comment by MasterOdin** [comment]
Do you know if this set-up worked using the python2 version of asciidoc (checking if a python regression) or is just something asciidoc-py never supported properly, or you do not know?

**Comment by bzbarsky-apple** [comment]
Hmm, I might have actually filed this in the wrong place... I am using "asciidoctor" to generate my rendered output.  Should I have filed this in https://github.com/asciidoctor/asciidoctor ?

**Comment by bzbarsky-apple** [comment]
Looks like I should have, yes.  Filed https://github.com/asciidoctor/asciidoctor/issues/3905

I don't know whether the python asciidoc has this problem...
