### ISSUE TITLE
Mac Homebrew formula?

### ISSUE THREAD

**Issue by apjanke** [asciidoc/asciidoc-py3#43]
Would you be interested in a Mac Homebrew formula for asciidoc-py3 so it could be easily installed on macOS? Might make it easier to get people to test it.

The [current Mac Homebrew `asciidoc` formula](https://formulae.brew.sh/formula/asciidoc) points to the Python2 implementation. Setting up a parallel formula could make migration to the Python3 version easier, assuming the port is successful.

>  if its only a single file that specifies installation then it probably isn't a problem.

It would be a single file (and maybe a README to go with it), but it needs to be maintained in a [separate repo that functions as a Homebrew "tap"](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md). This is their mechanism for supporting third-party formula definitions.

I've set up an example of how this could be done in my `apjanke/personal` tap here: https://github.com/apjanke/homebrew-personal/blob/70f8de6ab173170bc0e6088ba99599fb36001e1a/Formula/asciidoc-py3.rb. Once there are tagged releases of the py3 port, one could be added as the "devel" version, in addition to the "head" definition.

> And then is it possible to have the Python 2 entry advise using the -py3 version after its made available?

The asciidoc-py3 project looks a little young to be listed in core Homebrew yet.  But you could set up this "custom" asciidoc-py3 formula for use during the port/migration, and if the migration to py3 is successful, the main Homebrew asciidoc formula could be changed to use the new py3 version, which would migrate all the existing users over when they did a `brew upgrade`. Then the custom formula could then go away, unless you wanted to keep it around for testing pre-release versions.

-----

(Discussion migrated from https://github.com/asciidoc/asciidoc-py3/pull/40#issuecomment-430139312)

**Comment by MasterOdin** [comment]
Should the brew formula also include packages necessary to run some of the filters?

**Comment by apjanke** [comment]
> Or maybe just do a PR to update this to use the python3 version 

Yep, that's an option once there's a new stable release on this repo.

> Should the brew formula also include packages necessary to run some of the filters, or at least recommend installation of those packages?

Probably. Homebrew tends toward a maximalist "batteries included" installation. I'll take a look at the doco and see what packages are needed, and see about including them as dependencies.

Do you have an idea as to which filters are the most commonly used?

**Comment by MasterOdin** [comment]
> Probably. Homebrew tends toward a maximalist "batteries included" installation. I'll take a look at the doco and see what packages are needed, and see about including them as dependencies.
> 
> Do you have an idea as to which filters are the most commonly used?

I have no idea which filters are the most popular, but I can tell you the dependencies that are in homebrew core for the filters:
* graphviz: [graphviz](http://brewformulas.org/Graphviz)
* latex: none available, requires mactex which is available in homebrew cask and dvipng.
* music: [lilypond](http://brewformulas.org/Lilypond)
* source: [highlight](http://brewformulas.org/highlight) or [source-highlight](http://brewformulas.org/SourceHighlight) or pygments (no homebrew formula)

**Comment by FranklinYu** [comment]
Does this depend on #15?

**Comment by Bo98** [comment]
> Does this depend on #15?

Yes.

**Comment by MasterOdin** [comment]
PR submitted to homebrew for asciidoc 9.0.0: https://github.com/Homebrew/homebrew-core/pull/55660. This issue will be closed once that's merged.

**Comment by MasterOdin** [comment]
Merged, and now available.
