### ISSUE TITLE
Document Structure

### ISSUE THREAD

**Issue by GSebastian-Adil** [asciidoc/asciidoc-py3#48]
As I did with "Header Syntax" I tried the same with this topic, To make a better understanding of the Document Structure, The problem is: "I don't know to render this ascii into an image".
Thanks
[Document_Structure.txt](https://github.com/asciidoc/asciidoc-py3/files/2582981/Document_Structure.txt)

**Comment by elextr** [comment]
Thats not really an Asciidoc issue, you have to make your diagram using the format that some tool understands.  Maybe try the Graphviz tools.

**Comment by elextr** [comment]
If grafviz doesn't do it and google can't help I'm afraid I don't know a tool that will make those sorts of diagrams into images.
