### ISSUE TITLE
Allow use of custom XML catalogs

### ISSUE THREAD

**Issue by rossburton** [asciidoc/asciidoc-py3#61]
For reasons which are too tedious to go into, our XML default catalog doesn't have the docbook XML entries in.  We need to set `SGML_CATALOG_FILES` and pass `--catalogs` to xmllint but as asciidoc wraps xmllint that's harder.  I'm currently using this patch as a workaround:

```
diff --git a/a2x.py b/a2x.py
index 2d7699a..5bb995f 100755
--- a/a2x.py
+++ b/a2x.py
@@ -49,2 +49,4 @@ LYNX = 'lynx'               # alternate text file generator.
 XMLLINT = 'xmllint'         # Set to '' to disable.
+if "SGML_CATALOG_FILES" in os.environ:
+  XMLLINT += " --catalogs"
 EPUBCHECK = 'epubcheck'     # Set to '' to disable.
@@ -636,3 +638,3 @@ class A2X(AttrDict):
         if not self.no_xmllint and XMLLINT:
-            shell('"%s" --nonet --noout --valid "%s"' % (XMLLINT, docbook_file))
+            shell('%s --nonet --noout --valid "%s"' % (XMLLINT, docbook_file))
```

**Comment by rossburton** [comment]
No I'm not, that patch doesn't work.

**Comment by MasterOdin** [comment]
Marked this for 9.1.0.

Looking around the internet, it seems like the existence of this flag is a good signal that a user probably wants to have this be used for xmllint? I'm wondering if there's a case where a user would have this set and not want it to be used. An alternative would be to add a new command-line flag to a2x.
