### ISSUE TITLE
Use in a Python module

### ISSUE THREAD

**Issue by sharpaper** [asciidoc/asciidoc-py3#74]
How can I

1. import asciidoc-py3 in a existing python module
2. convert a asciidoc string to html

?? Thank you!

**Comment by MasterOdin** [comment]
I would look at the help strings at the top of the [asciidocapi.py](https://github.com/asciidoc/asciidoc-py3/blob/master/asciidocapi.py):
https://github.com/asciidoc/asciidoc-py3/blob/5b8771e2497ebfc70c93756d2afe9cd6f6c73641/asciidocapi.py#L17-L34

**Comment by sharpaper** [comment]
Out of curiosity, can the asciidoc module for Python3 be installed with pypi? Or do I have to download asciidocapi.py from this repository only?

**Comment by elextr** [comment]
Pypi is being worked on, but in the meantime from here.
