### ISSUE TITLE
dblatex replacement

### ISSUE THREAD

**Issue by jridky** [asciidoc/asciidoc-py3#76]
In Fedora, we're going to remove all Python2 packages due of Python2 EOL in 2020.

One of those packages is going to be dblatex, due upstream is quite dead for 2 years and no Python3 port of dblatex is available (at least I am not aware of it).

Do you plan to replace dblatex in asciidoc-py3? Is there any alternative?

**Comment by elextr** [comment]
Dblatex is a docbook toolchain, `asciidoc` generates the docbook for that toolchain to process, it doesn't use the toolchain itself.  The convenience script `a2x` does allow using the dblatex toolchain, but it also supports the FOP toolchain.

**Comment by jridky** [comment]
Thanks for prompt answer. So it's safe to get rid of dblatex and use FOP instead as default toolchain.

**Comment by elextr** [comment]
Well, yes the FOP toolchain can generate PDF like the dblatex one, but they are of course not a direct replacement since FOP doesn't use Latex so the configuring is different, and the FOP output looks very different to the Latex output, so don't expect that you won't get complaints :grin:.

**Comment by jridky** [comment]
Understand, but unless dblatex become Python3 compatible, I will not have any other option.

**Comment by elextr** [comment]
Note also that there may be other toolchains that handle docbook, for example I think [Pandoc](https://pandoc.org/#) can convert docbook to various things.  The toolchains themselves are beyond the scope of asciidoc though.

**Comment by MasterOdin** [comment]
Though it would somewhat ask that the default for PDF generation be changed from dblatex to something else?

**Comment by MasterOdin** [comment]
I've also reached out to the dblatex folks to see what their plans are on if they'd be open to a python3 port https://sourceforge.net/p/dblatex/mailman/dblatex-devel/thread/CAJEhc0zzNdoVcx15M%2BSi1ALg%2BmJ29QeuNg_u9Dj2%3Dr%2Bp3NBmwA%40mail.gmail.com/#msg36758452.

**Comment by MasterOdin** [comment]
Closing this as dblatex 0.3.11 (released a few months ago) now has py3 support and is going to be available in the next versions of all distros.
